flowchart TD
    A[Cultural Origins] --> B[Your Personality]
    B --> C[Clothing Style]
    C --> D[Hairstyle]
    D --> E[Affectation You Are Never Without]
    E --> F[What Do You Value Most?]
    F --> G[How Do You Feel About Most People?]
    G --> H[Most Valued Person in Your Life]
    H --> I[Most Valued Possession You Own]
    I --> J[Your Original Family Background]
    J --> K[Childhood Environment]
    K --> L[Your Family Crisis]
    L --> RM[How Many Friends?]
    RM --> M[Your Friends]
    M --> |Repeat for all friends|M
    M --> RN[How many enemies?]
    RN --> N[Enemy]
    N --> O[Who was wronged?]
    O --> P[What caused it?]
    P --> Q[What can they throw at you?]
    Q --> R[Sweet Revenge!]
    R --> |Repeat for all enemies|N
    R --> RS[How many love affairs?]
    RS --> S[Your Tragic Love Affairs]
    S --> |Repeat for all love affairs|S
    S --> T[Your Life Goals]
    
