flowchart TD
    A[Cultural Origins] --> B[Your Personality]
    B --> C[Clothing Style]
    C --> D[Hairstyle]
    D --> E[Affectation You Are Never Without]
    E --> F[What Do You Value Most?]
    F --> G[How Do You Feel About Most People?]
    G --> H[Most Valued Person in Your Life]
    H --> I[Most Valued Possession You Own]
    I --> J[Your Original Family Background]
    J --> K[Childhood Environment]
    K --> L[Your Family Crisis]
    L --> M[Your Friends]
    M --> N[Your Enemies]
    N --> O[Who was wronged?]
    O --> P[What caused it?]
    P --> Q[What can they throw at you?]
    Q --> R[Sweet Revenge!]
    R --> S[Your Tragic Love Affair(s)]
    S --> T[Your Life Goals]
