flowchart TD
    A[What Kind of Tech are You?] --> B[Got a Partner, or Do You Work Alone?]
    B -->|Work alone| C[What's Your Workspace Like?]
    B -->|Got a partner| D[If You Have a Partner, Who are They?]
    C --> E[Who are Your Main Clients?]
    D --> C
    E --> F[Where Do You Get Your Supplies?]
    F --> G[Who's Gunning For You?]
