flowchart TD
    A[What Kind of Corp Do You Work For?] --> B[What Division Do You Work In?]
    B --> C[How Good/Bad is Your Corp?]
    C --> D[Where is Your Corp Based?]
    D --> E[Who's Gunning for Your Group?]
    E --> F[Current State with Your Boss]
