flowchart TD
    A[What is Your Position on the Force?] --> B[How Wide is Your Group's Jurisdiction?]
    B --> C[How Corrupt is Your Group?]
    C --> D[Who's Gunning for Your Group?]
    D --> E[Who is Your Group's Major Target?]
