flowchart TD
    A[What Kind of Rockerboy are You?] --> B[Are You in a Group or a Solo Act?]
    B -->|Group| C[Where Do You Perform?]
    B -->|Solo| D[Were You Once in a Group?]
    D -->|Yes| E[Why Did You Leave?]
    C --> F[Who's Gunning for You/Your Group?]
    D --> F
    E --> F
