flowchart TD
    A[What Kind of Fixer are You?] --> B[Got a Partner or Work Alone?]
    B -->|Got a partner| C[Got a Partner? Who?]
    B -->|Work alone| D[What's Your &quot;Office&quot; Like?]
    C --> D
    D --> E[Who are Your Side Clients?]
    E --> F[Who's Gunning for You?]
