flowchart TD
    A[What Kind of Medtech are You?] --> B[Got a Partner, or Do You Work Alone?]
    B -->|Got a partner| C[Tell Us About Your Partners]
    B -->|Work alone| D[What's Your Workspace Like?]
    C --> D
    D --> E[Who are Your Main Clients?]
    E --> F[Where Do You Get Your Supplies?]
