flowchart TD
    A[What Kind of Runner are You?] --> B[Got a Partner, or Do You Work Alone?]
    B -->|Work alone| C[What's Your Workspace Like?]
    B -->|Got a partner| D[If You Have a Partner, Who are They?]
    C --> E[Who are Some of Your Other Clients?]
    D --> E
    E --> F[Where Do You Get Your Programs?]
    F --> G[Who's Gunning for You?]
