flowchart TD
    A[What Kind of Rockerboy are You?] --> B[Are You in a Group or a Solo Act?]
    B -->|Solo| C[Were You Once in a Group?]
    C -->|Yes| D[Why Did You Leave?]
    B -->|Group| E[Where Do You Perform?]
    D --> E
    C -->|No| E
    E --> F[Who's Gunning for You/Your Group?]
    